version: '3.8'

services:
  backend:
    image: space-taste-backend:0.1.0
    container_name: space-taste-backend
    mem_limit: 512M
    ports:
      - "4000:8080"
    environment:
      - "JAVA_OPTS=-Xmx160M -XX:MaxMetaspaceSize=64M -XX:ReservedCodeCacheSize=120M -Xss568K"
      - "SPRING_PROFILES_ACTIVE=docker"
      - "DATA_DIR=/app-data"
      - "JWT_SECRET=test"
    volumes:
      - "data:/app-data"
  db:
    image: mariadb:10.9
    container_name: space-taste-db
    mem_limit: 64M
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - "MARIADB_INITDB_SKIP_TZINFO=1"
      - "MARIADB_ROOT_HOST=localhost"
      - "MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1"
      - "MARIADB_AUTO_UPGRADE=1"
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:
  data:
