name: Android Build APK CI

on:
  push:
    branches: [ "main", "feat/LM-134" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: build prod
        run: ./gradlew :app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEYNAME }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Android APK
          path: app/build/outputs/apk/release/
