name: Docker Image Build CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build image
        run: ./gradlew :backend:bootBuildImage

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "space-taste-backend:0.1.0"
